module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'subject-case': [0, 'never'],
    'scope-empty': [1, 'never'],
    'scope-enum': [
      2,
      'always',
      [
        'plugin',
        'admin-component',
        'cals',
        'dev',
        'cdngo',
        'cli',
        'tea-console',
        'oa-website',
        'vuera',
        'builder',
        'generator',
        'render',
        'model-component',
        'weda-app',
        'portal',
        'client',
        'field-component',
        'weda-ui',
        'root',
        'tea-console-model',
        'tea-console-buy',
        'ide',
        'yehe',
        'weda-website',
        'weda-tcs-cms',
        'weda-sso',
        'local-cli',
        'weda-page-module-sdk',
      ],
    ],
  },
};
